### ISSUE TITLE
Dependencies not loading

### ISSUE THREAD

**Issue by danw1979** [rholder/gradle-view#12]
Installed on IDEA 14.1.3 on OS X 10.9.  Seemed to install OK, and Gradle View window opens OK, but list of project dependencies does not complete - it just says "Loading..." and doesn't go any further.  

![screen shot 2015-06-01 at 13 45 22](https://cloud.githubusercontent.com/assets/12696246/7913127/21112f04-0865-11e5-8268-d9f2afa00db7.png)

**Comment by rholder** [comment]
Is there anything in the log on the right side? Also, what versions of Java and Gradle are you using for your project?

**Comment by danw1979** [comment]
There's a blank panel on the right hand side of the Gradle View box, with nothing in it (screenshot) - is this where the log should be ?

![screen shot 2015-06-01 at 23 28 28](https://cloud.githubusercontent.com/assets/12696246/7932535/e68b7eb4-0910-11e5-9ab1-ad8c4ac04384.png)

I'm using Java 1.7 for the project.  Installed on this machine are 1.7.0_55 and 1.6.0_65, I've tried forcing IDEA to run under 1.6 and 1.7 but with no change in the Gradle View problem.    

The project gradle settings are "Use default gradle wrapper".  I'm not sure if this means use the project's gradle wrapper or IDEA's built-in gradle, but I suspect the latter (which I think is 2.2).

![screen shot 2015-06-02 at 09 34 53](https://cloud.githubusercontent.com/assets/12696246/7932539/f01c6f56-0910-11e5-8b54-76b27a155b15.png)

This particular Web project was initially a Maven project, converted using Gradle 2.4 using "gradle init".   I've also tried initialising a new IDEA project using a "default gradle wrapper" and also a "local gradle distribution" (2.4) both to no avail - same problem with Gradle View in both cases.

**Comment by childnode** [comment]
same here on WIndows, but: log tells me:
```
java.lang.RuntimeException: org.gradle.tooling.GradleConnectionException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.10-all.zip'.
	at com.github.rholder.gradle.dependency.DependencyConversionUtil.loadProjectDependenciesFromModel(DependencyConversionUtil.java:115)
	at com.github.rholder.gradle.intellij.DependencyViewer$1$1.doInBackground(DependencyViewer.java:106)
	at com.github.rholder.gradle.intellij.DependencyViewer$1$1.doInBackground(DependencyViewer.java:103)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.tooling.GradleConnectionException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.10-all.zip'.
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:59)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:46)
	at com.github.rholder.gradle.dependency.DependencyConversionUtil.loadProjectDependenciesFromModel(DependencyConversionUtil.java:109)
	... 8 more

Caused by: org.gradle.launcher.daemon.client.DaemonConnectionException: The newly created daemon process has a different context than expected.
It won't be possible to reconnect to this daemon. Context mismatch: 
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 15.0.3\jre,daemonRegistryDir=D:\Users\Marcel\.gradle\daemon,pid=11892,idleTimeout=null,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=DE,-Duser.language=de,-Duser.variant]
Actual: DefaultDaemonContext[uid=f421d4ca-0fbe-4af3-8b33-a88e934ab8ff,javaHome=C:\Program Files\Java\jre1.8.0_71,daemonRegistryDir=D:\Users\Marcel\.gradle\daemon,pid=12432,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=DE,-Duser.language=de,-Duser.variant]

	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToDaemonWithId(DefaultDaemonConnector.java:134)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:114)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:88)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:123)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:80)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:58)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:40)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:132)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:117)
	at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:190)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection$CancellableActionRunner.run(CancellableConsumerConnection.java:105)
	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:60)
	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:57)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	... 3 more
```

using wrapper, not using JDK in JAVA_HOME . Perhaps this helps to find some causes

**Comment by steveash** [comment]
I'm having the same problem with the gradle view plugin with this java home mismatch as reported above.  I've used this plugin successfully on other projects so I'm not sure if this is something related to a recent IDEA version (im on 2016.1.3)

```
java.lang.RuntimeException: org.gradle.tooling.GradleConnectionException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-all.zip'.
	at com.github.rholder.gradle.dependency.DependencyConversionUtil.loadProjectDependenciesFromModel(DependencyConversionUtil.java:115)
	at com.github.rholder.gradle.intellij.DependencyViewer$1$1.doInBackground(DependencyViewer.java:106)
	at com.github.rholder.gradle.intellij.DependencyViewer$1$1.doInBackground(DependencyViewer.java:103)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.tooling.GradleConnectionException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-all.zip'.
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:59)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:46)
	at com.github.rholder.gradle.dependency.DependencyConversionUtil.loadProjectDependenciesFromModel(DependencyConversionUtil.java:109)
	... 8 more
Caused by: org.gradle.launcher.daemon.client.DaemonConnectionException: The newly created daemon process has a different context than expected.
It won't be possible to reconnect to this daemon. Context mismatch: 
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=/home/steve/idea-IU-145.258.11/jre,daemonRegistryDir=/home/steve/.gradle/daemon,pid=null,idleTimeout=null,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=199f85dc-1eb1-4a68-8bac-13cd00398b97,javaHome=/usr/lib/jvm/java-8-oracle,daemonRegistryDir=/home/steve/.gradle/daemon,pid=16665,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]

	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToDaemonWithId(DefaultDaemonConnector.java:136)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:116)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:90)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:123)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:80)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:58)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:40)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:132)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:117)
	at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:190)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection$CancellableActionRunner.run(CancellableConsumerConnection.java:105)
	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:60)
	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:57)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	... 3 more
```

**Comment by steveash** [comment]
So looking at [DependencyUtil](https://github.com/rholder/gradle-view/blob/master/src/main/java/com/github/rholder/gradle/dependency/DependencyConversionUtil.java) I see that it just uses the java home that is in the environment variable. When I cat proc/<pid>/environ for IDEA I actually don't see JAVA_HOME set...which I don't know why that is... 

In any case a workaround that worked was modifying my idea64.vmoptions to add:
`-Dgradle.view.java.home=/usr/lib/jvm/java-8-oracle` as the code suggests as an override.  This java home is my real one (not the bundled IDEA jre) and this fixed the problem.

The SDK selected for this project is the same one /usr/lib/jvm/java-8-oracle.  Surely there is an easy way to get the java home path from IDEA and use that instead of just relying on JAVA_HOME ?  If I get some time I'll dig around and submit a pull request.

**Comment by mohamnag** [comment]
having the same problem with JAVA_HOME not being set on OS X. This plugin is the only one that needs this var being set. 
I also saw that this is actually using Gradle 2.3 which is not the one I'm using on my project. It simply seems that this plugin ignores the settings on the project and uses his own Gradle which is not really a good idea as lots of things may vary between these two.

**Comment by livizy** [comment]
Is this issue resolved?
I have the same problem.
