### ISSUE TITLE
on intellij 2019.3

### ISSUE THREAD

**Issue by igreenfield** [rholder/gradle-view#25]
java.lang.IllegalArgumentException: Could not determine java version from '11.0.4'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
	at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
	at org.gradle.tooling.internal.consumer.ConnectorServices.checkJavaVersion(ConnectorServices.java:57)
	at org.gradle.tooling.internal.consumer.ConnectorServices.createConnector(ConnectorServices.java:35)
	at org.gradle.tooling.GradleConnector.newConnector(GradleConnector.java:85)
	at com.github.rholder.gradle.dependency.DependencyConversionUtil.loadProjectDependenciesFromModel(DependencyConversionUtil.java:69)
	at com.github.rholder.gradle.intellij.DependencyViewer$1$1.doInBackground(DependencyViewer.java:106)
	at com.github.rholder.gradle.intellij.DependencyViewer$1$1.doInBackground(DependencyViewer.java:103)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by celroid** [comment]
I have the same problem. It seems Java 11 is not supported.

**Comment by rajvimalc** [comment]
This plugin is built on gradle-tooling-api 3.5.1 which is very old and does not support if IntelliJ Boot JRE is Java 9+. Also this repo author is not active, it seems. I have fixed the issues at my own fork. 

Close IntelliJ, extract the .zip file below and replace the 'gradle-view' folder at '%USERPROFILE%\.IdeaIC2019.2\config\plugins' and start IntelliJ.
https://github.com/rajvimalc/gradle-view/blob/master/build/distributions/gradle-view-4.0.0.zip
